name: Label dev PR

on:
  pull_request:
    types: 
      - opened
    branches:
      - master

jobs:
  put-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add master label
        uses: andymckay/labeler@master
        with:
          add-labels: master
