name: Label dev PR

on:
  pull_request:
    types: 
      - opened
    branches:
      - dev

jobs:
  put-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add dev label
        uses: andymckay/labeler@master
        with:
          add-labels: dev