name: Docker Image CI

on:
  release:
    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show ref
      run: echo ${GITHUB_REF}
    - name: Build the Docker image
      run: docker build . -f ./.github/workflows/Dockerfile -t actions-test
    - name: Run the Docker image
      run: docker run actions-test
