name: Docker Image CI

on:
  release:
    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker run hello-world
