name: Deploy a Docker container

on:
  registry_package:
    types:
      - published
      - updated
  push:
    branches:
      - master
    paths:
      - ".github/workflows/package.yaml"

permissions:
  contents: read

jobs:
  run:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Print incoming event
        run: |
          cat $GITHUB_EVENT_PATH
